<script setup lang="ts">
import Overlay from "./overlay.vue"


interface Emits {
  (event: "toggle-modal", data?: any): void
}

const emit = defineEmits<Emits>()


</script>
<template>
  <Overlay @toggle-overlay="emit('toggle-modal')">

    <fieldset class="box">
      <legend class="title">Command Table</legend>

      <fieldset id="concepts-box">
        <legend>Concepts</legend>

        <ul>
          <li>
            PROJECT-KEY: <br /> Key generated by your deta app in App settings. keep it secret do not share with others!
          </li>
          <li>
            ALIAS:
            <br /> Identifier that you create when adding a new project. This ALIAS is used to reference that project
            inside this app.
          </li>
          <li>
            BASE-NAME:
            <br /> One project can have multiple bases. BASE-NAME is the name that you use in your apps to get your data
          </li>


        </ul>

      </fieldset>
      <fieldset>
        <legend>Adding Projects and bases</legend>
        <p> * Deta Space does not provide list of projects and bases, you have to add it manually</p>
        <ul>
          <li>
            <b>>></b> /add-project ALIAS PROJECT-KEY
          </li>

          <li>
            <b>>></b> /add-base PROJECT-ALIAS BASE-NAME
          </li>
        </ul>

      </fieldset>
      <fieldset>
        <legend>Get more Project info</legend>

        <ul>
          <li>
            <b>>></b>
            /list-bases ALIAS
          </li>

        </ul>

      </fieldset>

      <fieldset>
        <legend> Display data</legend>

        <ul>
          <li>
            <b>>></b> /display ALIAS BASE-NAME
          </li>

        </ul>

      </fieldset>
      <fieldset>
        <legend>Base interactions</legend>

        <ul>
          <li>
            *Available soon !
          </li>

        </ul>

      </fieldset>


      <fieldset>
        <legend>Shortcuts</legend>

        <ul>

          <li>
            <div class="key-cap long-key">ctrl</div> + <div class="key-cap">O</div>
            <p>Add new Project</p>
          </li>
          <li>
            <div class="key-cap long-key">ctrl</div> + <div class="key-cap">I</div>
            <p>Add base to project</p>
          </li>
          <li>
            <div class="key-cap long-key">ctrl</div> + <div class="key-cap">K</div>
            <p>Focus command bar</p>
          </li>

          <li>
            <div class="key-cap long-key">ctrl</div> + <div class="key-cap">B</div>
            <p>Open command table</p>
          </li>

        </ul>

      </fieldset>
    </fieldset>
    <p class="exit-label">PRESS ESC TO EXIT</p>
  </Overlay>
</template>
<style scoped>
.box {
  width: 90%;
  height: 90%;
  overflow-y: scroll;
  border: solid 1px;
  border-radius: 1rem;
  display: grid;
  gap: 1rem;
  padding: 1rem;
  opacity: 1 !important;
  grid-auto-rows: 17rem;
  grid-auto-flow: dense;

  grid-template-columns: repeat(auto-fill, minmax(20rem, 1fr));
}

fieldset {
  height: 100%;
  width: 100%;
  border-radius: 0.5rem;
  border-color: var(--color);
  padding: 1rem;
  font-size: 0.9rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
  opacity: 0.7;
  overflow: scroll;
}

.exit-label {
  margin-top: 0.4rem;
}


.title {
  font-size: 1.3rem;
  width: fit-content;
  white-space: nowrap;
}

legend {
  width: fit-content;
  background-color: var(--bg-color);
  margin-left: 1rem;
  padding-inline: 0.3rem;

}



ul {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

li {
  display: flex;
  align-items: center;
  justify-content: start;
  gap: 0.5rem;
}

b {
  opacity: 0.4;
}

.key-cap {
  font-size: 1rem;
  padding: 1rem;

  border-radius: 0.2rem;
  border: solid 1px;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 2rem;
  height: 2rem;
  color: var(--color);
  opacity: 0.7;
}

.long-key {
  font-size: 0.6rem !important;
}
</style>